SvxLink
=======

image:https://travis-ci.org/sm0svx/svxlink.svg?branch=master["Build Status", link="https://travis-ci.org/sm0svx/svxlink"]
image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/sm0svx/svxlink?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

Fork der aktuellen Version von svxlink bei DL1HRC - Adi mit Änderungen in der Filter section. Diese Änderungen basieren auf der Entwicklertätigkeit von DL1JAE - Uwe und sind derzeitig noch nicht im MAIN bei svxlink eingearbeitet.

Eine aktuelle Beschreibung vom svxlink mit vielen Branches steht bei Adi im git-hub zur Verfügung:

https://github.com/dl1hrc/documentation

Zur Verarbeitung wechselt ihr am besten nach /home/svxlink und clont diese repo mit

git clone https://github.com/DB6KT/svxlink.git

beim ersten clonen wechselt ihr in das Verzeichnis svxlink und erstellt das build-Verzeichnis

cd svxlink/src

mkdir build

cd build

Starten von cmake wie folgt:

cmake -DUSE_QT=OFF -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc -DLOCAL_STATE_DIR=/var -DWITH_SYSTEMD=ON -DCMAKE_BUILD_TYPE=Release ..

weiter mit:

make

sudo make install

fertig!

Für ein späteres update der svxlink Software im Sachsenlink unter /home/svxlink

git pull

cd /src/build

Für den Fall, dass das build-Verzeichnis schon von früheren Installationsversuchen existieren
sollte und nicht leer ist empfiehlt sich zunächst ein:

make clean

und dann weiter mit

make

sudo make install



Für die Ansage der einzelnen Repeater bitte hier nachschauen

https://github.com/DB6KT/SachsLinkContrib

73 de Thomas
