SvxLink
=======

Die hier zur Verfügung gestellte Version svxlink ist speziell für die Repeater im SACHSENLINK 
erstellt worden. 
Dazu sind einige Änderungen in den Audiofiltern erfoderlich gewesen um eine gleiche Audioqualität über HF sowie 
über das Netzwerk zu garantieren. Vielen Dank an Uwe, DL1JAE für die Arbeit an der Audio und Adi, DL1HRC 
für die Softwarearbeit an svxlink.

Abhängigkeiten installieren (ich gehe von einer Arbeistumbegnung mit einem Raspberry Pi mit DEBIAN/Rasbian aus):
 
sudo apt install gcc g++ make cmake libgcrypt20-dev libgsm1-dev libsigc++-2.0-dev tcl-dev git libspeex-dev libasound2-dev libpopt-dev libssl-dev libopus-dev groff libcurl4-openssl-dev libjsoncpp-dev gpiod libgpiod-dev

sudo apt install alsa-base alsa-utils

unter /home/svxlink:

git clone https://github.com/DB6KT/svxlink.git

cd /svxlink/src

mkdir build

cd /build

Für den Fall, dass das build-Verzeichnis schon von früheren Installationsversuchen existieren sollte und nicht leer ist, empfiehlt sich zunächst ein:

make clean

danach weiter mit:

cmake -DUSE_QT=OFF -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc -DLOCAL_STATE_DIR=/var -DWITH_SYSTEMD=ON -DCMAKE_BUILD_TYPE=Release ..

make

sudo make install

ferdsch!

ACHTUNG - bitte auch die Erweiterungen installieren:

https://github.com/DB6KT/SachsLinkContrib.git

== Resources ==
These are some of the resources connected to SvxLink:

:gh_pages:    http://svxlink.org/
:gh_wiki:     https://github.com/sm0svx/svxlink/wiki
:gh_issues:   https://github.com/sm0svx/svxlink/issues
:gh_releases: https://github.com/sm0svx/svxlink/releases
:gh_sndclips: https://github.com/sm0svx/svxlink-sounds-en_US-heather/releases
:gh_main:     https://github.com/sm0svx/svxlink
:gi_svxlink:  https://groups.io/g/svxlink

* {gh_pages}[Project Home Page] -- The main project page
* {gh_wiki}[Wiki Pages] -- Main documentation
* {gh_issues}[Issue Tracker] -- Report bugs and feature requests
* {gh_releases}[Download Releases] -- Download source code releases here
* {gh_sndclips}[Download Sound Clips] -- Download English sound clip files for
  SvxLink Server from here
* {gh_main}[GitHub Main Page] -- The project site on GitHub
* {gi_svxlink}[Groups.io SvxLink] -- Communicate with other SvxLink users
